second commit
Neiluge06/LookDev_Tool pull request #1
Opened 2023-07-11 16:35 UTC by Neiluge06

Test

2023-07-11 16:50 UTC, gpijat requested changes
Need changes

2023-07-11 16:50 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +from maya import cmds as mc
N'inclus pas d'import a Maya dans le fichier UI, garde les dependances au software dans un fichier `core` externe. cf: lookDev_Core.py

2023-07-11 16:51 UTC, Neiluge06 commented on src/LookDev_Tool/lookDev_Ui.py
> +from maya import cmds as mc
ok

2023-07-12 15:26 UTC, gpijat commented on src/LookDev_Tool/lookDev_Core.py
> +        mc.createNode('camera', name='Main_Cam')
Je me demandais pourquoi tu as des `cmds.select(clear=True)` un peu partout, ca doit venir du fait que tu cree de nodes et que maya les selectionne, c'est bien ca ?
En fait, la commande `createNode` est un peu mal foutu, par default elle va select automatiquement le node cree et override ta selection, c'est pas vraiment ce que tu veux, par chance, tu peux utiliser le flag `skipSelect` et par consequent creer tes nodes sans changer la selection.

A noter que la selection en code request un refresh du viewport, et par consequent, ca reduit pas mal les perfs, car en rafraichissant le viewport, ca va egalement recompute une partie du Dependency Graph, ce que tu veux absolument eviter. Dans l'ideal, tu ne fais jamais de selection dans un script. Evidemment des fois, pas le choix, mais la, la question ne se pose pas.

2023-07-12 15:36 UTC, gpijat commented on src/LookDev_Tool/lookDev_Core.py
> +        mc.setKeyframe('Cam_Main_Grp', attribute='rotateY', time=float(numberOfFrames) / 2,
A priori, tu es en python 3, donc pas besoin d'avoir un float dans une expression pour que le resultat soit egalement un float.
Python 2.x: `1/2 --> 0`
Python 3.x: `1/2 --> 0.5`

Alors, c'est bien de maintenir si possible une backward compatibility, mais tu peux faire plus simple. Tu sais que dans une expression entre 2 int, au moins une de deux valeurs doit etre un float. Logiquement, ton `numberOfFrames` est un int, donc la tu le converti en float, pourquoi pas, semantiquement c'est ok.
Maintenant t'as plus simple, tu peux simplement au lieu de divide par `2` tu peux divide par `2.0` qui est un float.

`(float(numberOfFrames) / 2) == (numberOfFrames / 2.0)` Sera toujours `True`. Que tu sois en python 2 ou python 3. La difference c'est que dans le premier cas tu fais une conversion en plus.

2023-07-12 15:40 UTC, gpijat commented on src/LookDev_Tool/lookDev_Core.py
> +            mc.setAttr('ColorPalette_ALL_Grp.visibility', 1)
Ta logique ici est d'inverse la value de la visibility de `ColorPalette_ALL_Grp`.
Quoi qu'il arrive, si `Cam_Main_Grp` existe, tu va soit avoir la visibility en True et la mettre en False, soit l'inverse.

Tu peux faire plus simple:
`not cmds.getAttr('ColorPalette_ALL_Grp.visibility')` sera toujours l'inverse de l'etat actuel.

Tu peux simplifier comme ca:
```python
if mc.objExists('Cam_Main_Grp'):
    mc.setAttr('ColorPalette_ALL_Grp.visibility', not mc.getAttr('ColorPalette_ALL_Grp.visibility'))
```

2023-07-12 15:44 UTC, gpijat commented on src/LookDev_Tool/lookDev_Core.py
> +        raise RuntimeError(' Camera not in scene ')
Gardes en tete qu'un raise stop l'execution du code, donc la logique dans un script est de permettre a l'interpreter python de quitter le plus tot possible.
Ce que ca veut dire, c'est que tu peux t'arranger pour aider le flow du script et mettre les sortis de code le plus tot possible.
Ca peut aussi permettre de save des indentations, regarde:
```python
def hideColorPalette():

    if not mc.objExists('Cam_Main_Grp'):
        raise RuntimeError(' Camera not in scene ')

    mc.setAttr('ColorPalette_ALL_Grp.visibility', not mc.getAttr('ColorPalette_ALL_Grp.visibility'))
```

Dans cette fonction, le `setAttr` ne peut etre atteint que si t'as pas d'erreur, et donc que ton node existe.

2023-07-12 15:45 UTC, gpijat commented on src/LookDev_Tool/lookDev_Core.py
> +        raise RuntimeError(' Camera not in scene ')
Aussi, tu pourrais renommer la fonction `toggleColorPalette`, car c'est a priori ce qu'elle fait.

2023-07-12 17:00 UTC, Neiluge06 commented on src/LookDev_Tool/lookDev_Core.py
> +    queryTranslates = mc.xform(item1, query=True, translation=True, worldSpace=True)
J'avais le matrix dans la précédente version, mais il me semble que je n'avais pas besoin du rotate ( de tête ) du coup je l'ai enlevé

2023-07-12 17:01 UTC, Neiluge06 commented on src/LookDev_Tool/lookDev_Core.py
> +def ChangeColorSpace(colorSpace, *args):
my bad, j'ai oublié de l'enlever. à la base je crois que c'était que je mettait un partial, et du coup il me rajouter des args

2023-07-12 17:03 UTC, Neiluge06 commented on src/LookDev_Tool/lookDev_Core.py
> +    mc.select(clear=True)
Oui c'est ça, je voulais un bouton qui mette le ground et l'enlève quand tu rappuie dessus.

2023-07-12 17:22 UTC, Neiluge06 commented on src/LookDev_Tool/lookDev_Core.py
> +    with open("C:/Users/Moi/Documents/maya/2022/prefs/scripts/LookDev_Tool/prefs.json", 'r') as fileRead:
c'est à dire ? Je le met dans une variable ? comme avec "with open(preferencePath + "prefs.json", 'w') as wFile:" ?

2023-07-13 10:14 UTC, Neiluge06 commented on src/LookDev_Tool/lookDev_Core.py
> +            mc.setAttr('ColorPalette_ALL_Grp.visibility', 1)
aaah, je savais pas qu'on pouvait faire ça. Bien cool :)

2023-07-20 03:57 UTC, gpijat requested changes

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        super(JsUi, self).__init__(parent=maya_main_window())
Alors, je l'ai possiblement loupe, mais de ce que je vois, un peu plus haut, dans les arguments de ta methode `__init__` tu defini un argument `parent`, mais tu ne sembles pas l'utilise dans ton script.
Le principe de passer un parent a la classe, c'est de pouvoir parenter le widget que tu build a ce parent, directement a son initalisation.
Dans les faits, tu pourrais dans ton `__init__` faire `self.setParent(parent)`, `parent` etant le widget qui est passer a la methode. Mais ca ferait doublon, de base, le type `QWidget` dont inheritent tout les autres widget defini deja un comportement par defaut pour le parent, tu le vois dans ton super, tu fais `parent=maya_main_window()`, ca fonctionne justement car la methode `__init__` du type parent (QWidget) a aussi cet argument, et dans son body fais justement le parenting.

Bref, un gros pave juste pour dire que tu pourrais remplacer par: `super(JsUi, self).__init__(parent=parent)`.
Et lorsque tu build le widget: `JsUi(maya_main_window())`

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        self._ground_3_path = 'C:/Users/Moi/Documents/maya/' + self.maya_version \
Je te conseille d'eviter le split de ligne comme ca. Tu peux t'autoriser 80 (PEP8 classique), 100 ou 120 (C'est ok aussi, PEP8 proposait 80 a une epoque ou la plupart des gens etaient en 4:3 720p, c'est ok de mettre plus, c'est meme conseille, je respecte au mieux les 120 perso)

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        self.setStyleSheet()
Quel est le but de call cette methode ? Normalement tu dois justement lui donner une stylesheet, genre `self.setStyleSheet('background: rgb(0, 0, 0)')`

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        self.setLayout()
Pareil, setLayout il faut lui passer un layout.
Typiquement, quand tu cree ton "main layout", tu peux le faire de 2 manieres:
```python
self.mainLayout = QtWidgets.QHBoxLayout(self)  #1 
self.setLayout(QtWidgets.QHBoxLayout())  #2
```
Le layout est ensuite accessible via self.layout() qui return ton layout. Dans l'exemple au dessus si tu utilise la premiere methode tu peux aussi y faire reference via `self.mainLayout` vue que tu y a mis le layout manuellement.

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        self.rotateCamTitle.setFixedSize(90, 10)
Ca peut etre ok de faire ca, maintenant garde en tete que set la size c'est plus du `setup` que du `create`.
Tu pourrais split ton build en plus que le `createUi` et le `connectUi`.
Pour ma part je fais: `buildUi`, `setupUi` et `connectUi`, parfois meme un `refreshUi`. La plupart n'ont pas vocation  etre call par tes utilisateurs, tu peux en faire des methodes protected. (Genre `_createUi`, pour indiquer a toute personne utilisant ton code qu'il est preferable de pas y toucher)

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        self.setLayout()
Ok, plus loin je vois que tu as override cette methode, alors c'est pas tout a fait le but, le role de cette methode est de definir un layout dans ton widget, le parenter a ton widget si tu veux pour en faire le main layout.
Ce que tu fais dans ton override du setLayout semble etre le parenting, generalement ca prends place au meme endroit que la ou tu cree les widgets.

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        if self.setGroundMenu.currentIndex() == 2:
Rends tes condition exclusive, utilise `elif` et else.

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +        if not mc.objExists('Lights_Grp'):
if {not exist}: A / else B == if {exists} B / else A.

Et pour faire plus simple, cmds.objExists return un bool, True si l'obj exists, False otherwise.
Donc tu peux faire: `self.fillLightCheckBox.setChecked(cmds.objExists('Lights_Grp'))`

2023-07-20 03:57 UTC, gpijat commented on src/LookDev_Tool/lookDev_Ui.py
> +            self.lightDomeRotateLabel.setText('0')
2 choses, tes 2 premieres instructions, que ce soit True ou False, sont les meme, donc ne les ecris pas 2 fois, mets les juste hors de la condition.
Ensuite, tu verifie que l'obj n'existes pas, tu fais un truc, sinon tu fais autre chose, comme dis plus haut: `if {not exist}: A / else B == if {exists} B / else A`. Autant check si l'obj exists, et le else est le cas si l'obj n'existes pas.

Pour aller un peu plus loin, meme tips que plus haut, tu mets un 0 ou un 1 dans les attr, que ce soit str ou int, mais au final t'a sun bool, qui est a True ou False, soit 0 ou 1. Tu pourrais essayer `self.lightDomeIntensSlider.setValue(int(mc.objExists('JS_lightDome')))`

2023-10-31 11:16 UTC, merged